// The Traditions wing: which passages, in course order, per the plan's core
// selections. Four weekly themes; 25–40 passages per tradition.
// Each entry names an extractor (kind) in scripts/ingest-traditions.mjs and
// where the words are; the words themselves always come from the source.

export const WEEKS = [
  { n: 1, theme: "Foundations", covers: "Origins, key figures, scripture, core beliefs, how it's practised today" },
  { n: 2, theme: "Ethics", covers: "How to treat others: justice, mercy, charity, forgiveness" },
  { n: 3, theme: "The self", covers: "Pride and humility, desire, suffering, death" },
  { n: 4, theme: "Purpose and practice", covers: "Duty and work, prayer or meditation, community, the goal of life" },
];

const jps = (week, book, ch, v, extra = {}) => ({ week, kind: "jps", book, ch, v, ...extra });
const avot = (week, ch, m) => ({ week, kind: "avot", ch, m });
const web = (week, book, ch, v) => ({ week, kind: "web", book, ch, v, work: "New Testament" });
const imit = (week, book, chapter, start, end) => ({ week, kind: "imitation", book, chapter, start, end });
const q = (week, s, v) => ({ week, kind: "quran", s, v });
const gita = (week, ch, verses, start, end) => ({ week, kind: "gita", ch, start, end, label: `Bhagavad Gita ${ch}.${verses}` });
const upa = (week, name, part, parts) => ({ week, kind: "upanishad", name, part, parts });
const sutta = (week, uid, from, to, title, verse = false) => ({ week, kind: "sutta", uid, from, to, title, verse });
const card = (week, ref_id) => ({ week, ref_id }); // a card already in the library

export const TRADITIONS = [
  {
    id: "judaism", name: "Judaism", work: "Tanakh and Pirkei Avot", year: "c. 1000–200 BC",
    why: "Covenant, justice and study; the root of the Abrahamic traditions",
    blurb: "The Hebrew Bible in the 1917 Jewish Publication Society translation, and the sayings of the rabbis in Pirkei Avot.",
    selections: [
      jps(1, "Genesis", 1, "1-5"),
      jps(1, "Genesis", 1, "26-28"),
      jps(1, "Genesis", 12, "1-3"),
      jps(1, "Exodus", 20, "2-7"),
      jps(1, "Exodus", 20, "8-14"),
      jps(1, "Deuteronomy", 6, "4-9"),
      avot(1, 1, 1),
      jps(1, "Deuteronomy", 30, "11-14"),
      jps(1, "Deuteronomy", 30, "19-20"),
      jps(2, "Leviticus", 19, "17-18"),
      jps(2, "Leviticus", 19, "33-34"),
      jps(2, "Micah", 6, 8),
      jps(2, "Isaiah", 58, "6-8"),
      jps(2, "Deuteronomy", 16, "18-20"),
      jps(2, "Deuteronomy", 15, "7-8"),
      jps(2, "Proverbs", 25, "21-22", { lines: true }),
      avot(2, 1, 2),
      avot(2, 1, 18),
      avot(2, 2, 4),
      jps(3, "Psalms", 8, "4-7", { lines: true }),
      jps(3, "Psalms", 90, "10-12", { lines: true }),
      jps(3, "Ecclesiastes", 1, "2-4", { lines: true }),
      jps(3, "Ecclesiastes", 3, "1-8", { lines: true }),
      jps(3, "Proverbs", 16, "18-19", { lines: true }),
      jps(3, "Proverbs", 16, 32),
      avot(3, 4, 1),
      avot(3, 3, 1),
      jps(3, "Psalms", 23, "1-6", { lines: true }),
      jps(4, "Psalms", 1, "1-3", { lines: true }),
      avot(4, 1, 14),
      avot(4, 1, 15),
      avot(4, 2, "15-16"),
      jps(4, "Isaiah", 2, 4),
      jps(4, "Ecclesiastes", 9, 10),
      jps(4, "Ecclesiastes", 12, 13),
      jps(4, "Psalms", 133, 1),
    ],
  },
  {
    id: "christianity", name: "Christianity", work: "New Testament and The Imitation of Christ", year: "c. AD 30–100",
    why: "Love of God and neighbour; grace and service",
    blurb: "The teaching of Jesus and the early church in the World English Bible, with Thomas à Kempis's Imitation of Christ.",
    selections: [
      web(1, "Mark", 1, "14-15"),
      web(1, "John", 1, "1-5"),
      web(1, "John", 1, 14),
      web(1, "Matthew", 5, "3-10"),
      web(1, "Matthew", 22, "36-40"),
      web(1, "John", 3, "16-17"),
      web(1, "Luke", 4, "18-19"),
      web(1, "Acts", 2, "44-47"),
      web(1, "Matthew", 16, "24-26"),
      web(2, "Matthew", 5, "38-42"),
      web(2, "Matthew", 5, "43-48"),
      web(2, "Matthew", 7, 12),
      web(2, "Matthew", 7, "1-5"),
      web(2, "Luke", 10, "29-37"),
      web(2, "Matthew", 6, "1-4"),
      web(2, "Matthew", 18, "21-22"),
      web(2, "Matthew", 25, "34-40"),
      web(2, "1Corinthians", 13, "4-7"),
      web(2, "Luke", 6, "36-38"),
      web(3, "Matthew", 6, "19-21"),
      web(3, "Matthew", 6, "25-27"),
      web(3, "Matthew", 6, "33-34"),
      web(3, "Luke", 15, "11-19"),
      web(3, "Luke", 15, "20-24"),
      web(3, "Luke", 18, "9-14"),
      web(3, "James", 4, "13-15"),
      web(3, "Philippians", 4, "11-13"),
      imit(3, 1, 2, "There is naturally in every man a desire to know", "who is to judge me according to my deeds?"),
      imit(3, 1, 1, "What doth it profit thee to enter into deep discussion", "to reach forward to the heavenly kingdom."),
      web(4, "Matthew", 6, "6-13"),
      web(4, "Matthew", 5, "14-16"),
      web(4, "Matthew", 7, "24-27"),
      web(4, "Matthew", 20, "25-28"),
      web(4, "Romans", 12, "9-18"),
      web(4, "Colossians", 3, "23-24"),
      web(4, "James", 1, "22-25"),
      web(4, "Galatians", 5, "22-23"),
      imit(4, 1, 23, "Very quickly will there be an end of thee here", "as if thou wert to die this day."),
    ],
  },
  {
    id: "islam", name: "Islam", work: "Quran", year: "AD 610–632",
    why: "Submission to one God; justice, mercy and charity",
    blurb: "The Quran in Marmaduke Pickthall's 1930 translation, with the Arabic text alongside.",
    selections: [
      q(1, 1, "1-7"),
      q(1, 112, "1-4"),
      q(1, 2, 255),
      q(1, 2, 256),
      q(1, 96, "1-5"),
      q(1, 2, "2-5"),
      q(1, 59, "22-24"),
      q(1, 2, 186),
      q(1, 30, 22),
      q(2, 2, 177),
      q(2, 4, 135),
      q(2, 5, 8),
      q(2, 2, "263-264"),
      q(2, 49, 13),
      q(2, 49, "11-12"),
      q(2, 17, "23-24"),
      q(2, 41, "34-35"),
      q(2, 5, 32),
      q(2, 16, 90),
      q(3, 31, "12-15"),
      q(3, 31, "16-19"),
      q(3, 94, "1-8"),
      q(3, 103, "1-3"),
      q(3, 2, 286),
      q(3, 57, 20),
      q(3, 3, 185),
      q(3, 2, "155-157"),
      q(3, 13, 11),
      q(3, 25, 63),
      q(4, 2, "45-46"),
      q(4, 29, 45),
      q(4, 62, "9-10"),
      q(4, 2, 183),
      q(4, 3, 103),
      q(4, 17, 37),
      q(4, 20, 114),
      q(4, 51, 56),
    ],
  },
  {
    id: "hinduism", name: "Hinduism", work: "Bhagavad Gita and Upanishads", year: "c. 800–200 BC",
    why: "Duty without attachment; the Self behind all things",
    blurb: "The Bhagavad Gita in Kisari Mohan Ganguli's translation of the Mahabharata, and the Isha, Katha and Kena Upanishads translated by Swami Paramananda.",
    selections: [
      gita(1, 2, "11–13", "Thou mournest those that deserve not to be mourned.", "so (also) is the acquisition of another body."),
      gita(1, 2, "19–22", "He who thinks it (the soul) to be the slayer", "entereth other bodies that are new."),
      gita(1, 4, "7–8", "Whenever, O Bharata, loss of piety", "I am born age after age."),
      upa(1, "Isha", "1", [["All this, whatsoever exists in the universe", "Do not covet the wealth of any man."]]),
      upa(1, "Isha", "6–7", [["He who sees all beings in the Self and the Self in all beings", "never turns away from It (the Self)."], ["He who perceives all beings as the Self", "when he sees this oneness (everywhere)?"]]),
      upa(1, "Kena", "1.4–6", [["That which speech does not illumine", "not this which people worship here."], ["That which cannot be thought by mind", "not this which people worship here."], ["That which is not seen by the eye", "not this which people worship here."]]),
      upa(1, "Katha", "1.3.3–4", [["Know the Atman (Self) as the lord of the chariot", "mind the reins."], ["The senses are called the horses", "the wise call Him the enjoyer."]]),
      gita(1, 9, "26–27", "They who offer me with reverence, leaf, flower, fruit, water", "that it may be an offering to me."),
      gita(2, 16, "1–3", "Fearlessness, purity of heart", "who is born to godlike possessions."),
      gita(2, 5, "18", "Those, who are wise cast an equal eye", "a dog, and a chandala."),
      gita(2, 12, "13–15", "He who hath no hatred for any creature", "even he is dear to me. He through whom the world is not troubled, (and) who is not troubled by the world, who is free from joy, wrath, fear and anxieties, even he is dear to me."),
      gita(2, 17, "15–16", "The speech which causeth no agitation", "are said to be the penance of the mind."),
      gita(2, 3, "19–21", "Therefore, always do work that should be done, without attachment.", "Ordinary men follow the ideal set by them (the great)."),
      gita(2, 6, "9", "He, who views equally well-wishers, friends, foes", "is distinguished (above all others)."),
      gita(3, 2, "14–15", "The contacts of the senses with their (respective) objects", "is fit for emancipation."),
      gita(3, 2, "62–63", "Thinking of the objects of sense, a person's attachment is begotten towards them.", "is utterly ruined."),
      gita(3, 2, "70", "He into whom all objects of desire enter", "and not one that longeth for objects of desire."),
      gita(3, 6, "5–7", "One should raise (his) self by self;", "honour and dishonour."),
      gita(3, 6, "19", "As a lamp in a windless spot doth not flicker", "who applieth his self to abstraction."),
      gita(3, 6, "34", "O Krishna, the mind is restless", "as the restraint of the wind."),
      upa(3, "Katha", "1.2.1–2", [["Yama said: The good is one thing and the pleasant another.", "misses the true end."], ["The good and the pleasant approach man", "through love of bodily pleasure."]]),
      gita(3, 18, "38", "That which is from the contact of the senses with their objects", "is held to be of the quality of passion."),
      gita(4, 2, "47–48", "Thy concern is with work only, but not with the fruit (of work).", "This equanimity is called Yoga (devotion)."),
      gita(4, 2, "50–51", "Devotion is only cleverness in action.", "attain to that region where there is no unhappiness."),
      gita(4, 3, "35", "One's own duty, even if imperfectly performed", "carries fear (with it)."),
      gita(4, 4, "20", "Whoever, resigning all attachment to the fruit of action", "doth nought, indeed, although engaged in action."),
      gita(4, 5, "10", "He who renouncing attachment engageth in actions", "(is not touched) by water."),
      gita(4, 6, "16–17", "Devotion is not one's, O Arjuna, who eateth much", "temperate in sleep and vigils."),
      gita(4, 18, "11", "Since actions cannot be absolutely abandoned by an embodied person", "is truly said to be an abandoner."),
      upa(4, "Katha", "1.3.14", [["Arise! Awake! Having reached the Great Ones", "so the wise declare."]]),
    ],
  },
  {
    id: "buddhism", name: "Buddhism", work: "Suttas and the Dhammapada", year: "c. 500 BC",
    why: "Suffering, its cause and its end; the middle way",
    blurb: "Discourses of the Buddha from the Pali canon in Bhikkhu Sujato's translation, with the Dhammapada in Max Müller's.",
    selections: [
      sutta(1, "sn56.11", "2.1", "3.4", "Rolling Forth the Wheel of Dhamma"),
      sutta(1, "sn56.11", "4.1", "4.10", "The Four Noble Truths"),
      card(1, "dhammapada.1"),
      sutta(1, "an3.65", "4.1", "4.3", "With the Kālāmas"),
      sutta(1, "sn56.11", "11.1", "11.2", "Everything That Arises"),
      sutta(1, "dn16", "2.26.1", "2.26.1", "Be Your Own Island"),
      card(1, "dhammapada.89"),
      sutta(2, "snp1.8", "1.1", "5.4", "The Discourse on Love", true),
      sutta(2, "snp1.8", "6.1", "9.4", "The Discourse on Love (continued)", true),
      card(2, "dhammapada.2"),
      sutta(2, "mn21", "20.1", "20.5", "The Simile of the Saw"),
      sutta(2, "sn47.19", "1.3", "2.4", "The Acrobat"),
      card(2, "dhammapada.74"),
      sutta(2, "sn45.2", "1.4", "2.3", "Good Friends"),
      card(2, "dhammapada.63"),
      sutta(3, "sn36.6", "1.5", "1.10", "The Second Arrow"),
      sutta(3, "sn36.6", "2.1", "3.3", "The Second Arrow (the trained mind)"),
      sutta(3, "an5.57", "1.2", "1.9", "Five Subjects for Frequent Reflection"),
      sutta(3, "an5.57", "2.1", "2.4", "The Vanity of Youth"),
      card(3, "dhammapada.36"),
      card(3, "dhammapada.91"),
      sutta(3, "mn61", "8.1", "9.3", "The Mirror"),
      card(3, "dhammapada.21"),
      sutta(4, "mn10", "2.1", "3.5", "Mindfulness Meditation"),
      sutta(4, "an8.54", "2.1", "2.8", "A Householder's Welfare: Initiative"),
      sutta(4, "an8.54", "5.1", "5.8", "A Householder's Welfare: Balanced Finances"),
      card(4, "dhammapada.62"),
      card(4, "dhammapada.90"),
      card(4, "dhammapada.28"),
      sutta(4, "dn16", "6.7.1", "6.7.4", "The Buddha's Last Words"),
    ],
  },
];
