// Traditions wing explainers: Christianity (World English Bible; The Imitation of Christ, Benham 1874).
// Beliefs are described as the tradition holds them; no ranking of traditions.
export default {
  "christianity.1": {
    meaning: "After John the Baptist is arrested, Jesus begins preaching in Galilee: the time has come, God's Kingdom is near, so turn around and believe the good news.",
    context: "Mark is usually thought to be the earliest Gospel, written around AD 65–70. Repent translates metanoia, literally a change of mind or direction. The Kingdom of God, God's rule breaking into the world, is the centre of Jesus's teaching; Christians differ on how much it is present now and how much it awaits the future.",
    today: "Change often starts with a fresh reading of the moment: now is the time, so change direction.",
    you: "Where do you need a metanoia, a real change of direction rather than a small adjustment? Name it this week.",
  },
  "christianity.2": {
    meaning: "In the beginning was the Word, who was with God and was God. Everything was made through him. In him was life, and that life was the light of humanity, shining in darkness that has not overcome it.",
    context: "John's Gospel opens by echoing Genesis. Word translates logos, a term Greek philosophers, including the Stoics, used for the rational order of the universe. Christians read the Word as the eternal Son of God; this passage became central to the doctrine of the Trinity shared by Catholic, Orthodox and most Protestant churches.",
    today: "The idea of an ordering reason behind the world connects ancient philosophy, faith and the scientific search for laws.",
    you: "Notice the link with your Stoic reading: Marcus's logos and John's Word use the same Greek term, with different meanings. Hold both in view.",
  },
  "christianity.3": {
    meaning: "The Word became a human being and lived among us. We saw his glory, the glory of the Father's only Son, full of grace and truth.",
    context: "This is the doctrine of the Incarnation: God taking on human flesh in Jesus. Lived among us literally means pitched his tent, recalling God's presence in the tabernacle. Christmas celebrates it. Christian traditions agree on the Incarnation, while earlier councils, like Chalcedon in AD 451, defined it and caused some churches to separate.",
    today: "Truth that is lived, embodied, is more convincing than truth that is only spoken.",
    you: "Lead by embodiment: be present among your team, in their spaces, not only in directives from a distance.",
  },
  "christianity.4": {
    meaning: "The Beatitudes: blessed are the poor in spirit, those who mourn, the gentle, those hungry for righteousness, the merciful, the pure in heart, the peacemakers, and those persecuted for doing right. Each is promised a reward in God's Kingdom.",
    context: "These open the Sermon on the Mount in Matthew 5–7, the fullest collection of Jesus's ethical teaching. Blessed, makarios, means deeply fortunate. The Beatitudes reverse worldly values; Catholic and Orthodox readers often treat them as a path to holiness, while many Protestants stress them as a description of those already living under grace.",
    today: "It's a radical list of who counts as fortunate, running against a culture that celebrates the powerful and the loud.",
    you: "As a leader in defence and public service, note the blessing on peacemakers. Ask how your work serves peace in the end.",
  },
  "christianity.5": {
    meaning: "Asked which is the greatest commandment, Jesus answers: love God with all your heart, soul and mind; and the second is like it: love your neighbour as yourself. All the law and the prophets hang on these two.",
    context: "Jesus quotes two texts from the Hebrew Bible: the Shema in Deuteronomy 6 and Leviticus 19:18. Christians of every branch treat these two commandments as the summary of their ethics. The word for love here, agape, came to mean self-giving love.",
    today: "Many ethical systems reduce to love of the highest good and love of others. It's a compass that fits in one sentence.",
    you: "When you're unsure what to do, ask the two questions: what honours what's highest, and what truly serves the people affected?",
  },
  "christianity.6": {
    meaning: "God loved the world so much that he gave his only Son, so that whoever believes in him won't perish but will have eternal life. God didn't send his Son to condemn the world, but to save it.",
    context: "John 3:16 is probably the most quoted verse in the New Testament, often called the Gospel in miniature. It expresses the Christian belief that God's love is the motive for the life and death of Jesus. Traditions differ on how salvation is received: through faith alone for many Protestants, and through faith joined with sacraments and works for Catholic and Orthodox Christians.",
    today: "The idea that ultimate reality is loving, not condemning, has shaped Western ideas of grace and second chances.",
    you: "When someone on your team fails, lead with the aim of rescue, not condemnation. It's the posture this verse describes.",
  },
  "christianity.7": {
    meaning: "Jesus reads from Isaiah in the synagogue at Nazareth: the Spirit has anointed him to bring good news to the poor, heal the broken-hearted, proclaim freedom to captives, sight to the blind, liberty to the oppressed, and the year of the Lord's favour.",
    context: "Luke presents this as Jesus's mission statement. The year of favour recalls the Jubilee in Leviticus, when debts were cancelled and land returned. Liberation theology in Latin America and Christian social movements draw heavily on this passage.",
    today: "Mission statements matter. This one centres the poor, the captive and the oppressed.",
    you: "Write your own one-paragraph mission for this phase of your career. Who is it for?",
  },
  "christianity.8": {
    meaning: "The first believers shared everything, sold property to give to anyone in need, met daily in the temple, broke bread in their homes with glad and generous hearts, and were liked by everyone.",
    context: "Acts, by the author of Luke, describes the church in Jerusalem after Pentecost. Christians debate whether this sharing was a model for all or a special moment. Monastic communities took it as their pattern; many churches see it as a call to generosity rather than common ownership.",
    today: "Communities built on shared meals and mutual help remain the healthiest kind.",
    you: "Break bread with your team or neighbours this month. Shared meals build the trust that formal structures can't.",
  },
  "christianity.9": {
    meaning: "Whoever wants to follow Jesus must deny himself, take up his cross and follow. Whoever tries to save his life will lose it, and whoever loses it for his sake will find it. What good is it to gain the whole world and lose your soul?",
    context: "Taking up the cross meant, to first-century hearers, walking to execution. Christians read it as self-denial and costly loyalty. The question about gaining the world and losing the soul has been a touchstone for Christian thinking about ambition.",
    today: "Success that costs your integrity or your inner life is a bad bargain.",
    you: "Ask of your career ambitions: what would it profit me to reach the top and lose my family or my integrity on the way?",
  },
  "christianity.10": {
    meaning: "You've heard eye for eye, tooth for tooth. But Jesus says: don't resist an evil person. If someone strikes your right cheek, turn the other. If sued for your coat, give your cloak too. Go the extra mile, and give to those who ask.",
    context: "Eye for an eye, from the Torah, originally limited revenge to proportion. Jesus goes further. Scholars note that a blow to the right cheek implies a backhanded insult, so turning the other cheek refuses humiliation without violence. Christians differ on what this means for states and soldiers: pacifist churches like the Quakers read it literally, while most traditions developed just-war thinking for public duties.",
    today: "Refusing to escalate can break cycles of retaliation, in families and between nations.",
    you: "In defence work, this is a live tension. Most Christian traditions distinguish personal non-retaliation from the state's duty to protect. Know where you stand.",
  },
  "christianity.11": {
    meaning: "You've heard, love your neighbour and hate your enemy. But Jesus says: love your enemies and pray for those who persecute you. God sends sun and rain on good and bad alike. If you love only those who love you, what's special? Be perfect, as your Father is perfect.",
    context: "Love of enemies is one of the most distinctive teachings of Jesus. Perfect, teleios, means complete or mature. Martin Luther King Jr. drew on this passage in the civil-rights movement, arguing love could transform opponents.",
    today: "Treating opponents with goodwill is harder than tolerance, and far more transformative.",
    you: "Pray for, or simply wish well, someone who has opposed you at work. See whether it changes how you deal with them.",
  },
  "christianity.12": {
    meaning: "Whatever you want others to do to you, do also to them. This sums up the law and the prophets.",
    context: "This is the Golden Rule in its positive form. Hillel had stated the negative form: what is hateful to you, don't do to others. Confucius, the Mahabharata and Islamic tradition have close parallels, making it one of the most widely shared ethical principles.",
    today: "It asks for initiative, not just restraint: do the good you'd want, rather than merely avoid harm.",
    you: "This week, do for a colleague the thing you'd most appreciate having done for you: an introduction, credit, a heads-up.",
  },
  "christianity.13": {
    meaning: "Don't judge, or you'll be judged by the same measure. Why notice the speck in your brother's eye and ignore the plank in your own? First remove your plank; then you'll see clearly to help with his speck.",
    context: "This doesn't forbid all moral judgement: Jesus goes on to call people to discern. It targets hypocrisy and harshness. The image is deliberately comic, a plank in the eye, to make self-righteousness absurd.",
    today: "We see others' faults easily and ours hardly at all. Self-examination makes criticism fairer and more useful.",
    you: "Before a performance conversation, write down your own contribution to the problem. Then you'll see clearly.",
  },
  "christianity.14": {
    meaning: "Asked who counts as his neighbour, Jesus tells of a man beaten by robbers. A priest and a Levite pass by. A Samaritan, from a despised group, stops, bandages him, takes him to an inn and pays for his care. Which was the neighbour? The one who showed mercy. Go and do the same.",
    context: "Jews and Samaritans were bitter rivals, so the hero is a deliberate shock. The parable changes the question from whom must I love to whom can I be a neighbour. It gave the world the phrase Good Samaritan and influenced laws protecting those who help strangers.",
    today: "Compassion across tribal lines is the real test of goodness.",
    you: "Who in your world is on the other side of a line, another agency, another party? Be the neighbour who stops.",
  },
  "christianity.15": {
    meaning: "Don't give to charity in order to be seen. When you give, don't sound a trumpet as the hypocrites do; don't let your left hand know what your right is doing. Give in secret, and your Father who sees in secret will reward you.",
    context: "Hypocrite, hypokrites, meant a stage actor. Jesus contrasts performed piety with hidden goodness. This teaching parallels Marcus Aurelius on doing good like a vine bearing grapes, and Islamic and Jewish warnings about charity for show.",
    today: "Social media makes virtue a performance. Anonymous giving keeps the motive clean.",
    you: "Do one good thing this week that nobody will ever know about. It's the antidote to the Metric Cage.",
  },
  "christianity.16": {
    meaning: "Peter asks how often he must forgive his brother: up to seven times? Jesus says: not seven, but seventy times seven.",
    context: "Seven was already generous by the standards of the day. Seventy times seven, or seventy-seven in some readings, means without limit. Forgiveness is central to Christian practice across traditions, including in the Lord's Prayer; Catholic and Orthodox Christians also practise it through the sacrament of confession.",
    today: "Forgiveness frees the forgiver from carrying the offence.",
    you: "Think of someone you've forgiven only partially. Forgive them again, fully. Notice what it lifts from you.",
  },
  "christianity.17": {
    meaning: "The King welcomes the righteous: I was hungry and you fed me, thirsty and you gave me drink, a stranger and you took me in, naked and you clothed me, sick and in prison and you visited me. When did we do this? Whatever you did for the least of these, you did for me.",
    context: "This is the parable of the sheep and the goats, about final judgement. It grounds the Christian works of mercy: feeding, clothing, sheltering and visiting. Catholic social teaching and many Protestant charities cite it; it suggests Christ is encountered in people in need.",
    today: "How we treat the least powerful reveals what we really value.",
    you: "Visit someone who's easy to forget: a sick colleague, a veteran, an elderly relative. It counts more than you think.",
  },
  "christianity.18": {
    meaning: "Love is patient and kind. It doesn't envy, boast or act proud. It isn't rude, self-seeking or easily angered, and keeps no record of wrongs. It doesn't delight in evil but rejoices with the truth. It bears, believes, hopes and endures all things.",
    context: "Paul wrote this to the divided church at Corinth around AD 55. It's famous from weddings, but Paul meant it for a community quarrelling over status and spiritual gifts. The love described is agape, self-giving goodwill, rather than romance.",
    today: "It's a practical checklist for any relationship or team under strain.",
    you: "Read the list as a leadership audit: patient, not boastful, keeping no record of wrongs. Which is weakest for you right now?",
  },
  "christianity.19": {
    meaning: "Be merciful, as your Father is merciful. Don't judge or condemn, and you won't be. Forgive and you'll be forgiven. Give, and it will be given to you, a full measure, pressed down and running over; the measure you use will be used for you.",
    context: "Luke's version of Jesus's teaching, from the Sermon on the Plain. The image is of grain poured generously into a fold of clothing. Christian traditions read the reciprocity as a principle of God's generosity rather than a transaction.",
    today: "Generous people tend to be treated generously. Stingy judgement comes back to us too.",
    you: "Use a generous measure with your team: give credit, forgive errors, assume good intent. See what comes back.",
  },
  "christianity.20": {
    meaning: "Don't store up treasures on earth, where moth and rust destroy and thieves break in. Store up treasures in heaven, where they're safe. Where your treasure is, there your heart will be too.",
    context: "Jesus warns about the pull of wealth. Christian traditions, from monastic poverty to Protestant stewardship, interpret it differently, but all read it as a call to hold possessions loosely and invest in what lasts.",
    today: "Where we spend our money and attention shows where our heart is.",
    you: "Check your calendar and bank statement: they reveal your treasure. Do they match what you say matters?",
  },
  "christianity.21": {
    meaning: "Don't worry about what you'll eat, drink or wear. Isn't life more than food, the body more than clothes? Look at the birds: they don't sow or store, yet God feeds them. Aren't you worth more? Can worrying add an hour to your life?",
    context: "This passage from the Sermon on the Mount addresses anxiety directly. It isn't against work, which Christianity values, but against worry that distorts priorities. Many Christians read it alongside Paul's instruction to bring requests to God in prayer rather than be anxious.",
    today: "Anxiety rarely changes outcomes. It steals the present.",
    you: "When worry about work or money spikes, ask Jesus's question: can this worry add a single hour? Then act on what you can.",
  },
  "christianity.22": {
    meaning: "Seek first God's Kingdom and his righteousness, and everything else will be given to you as well. So don't worry about tomorrow; tomorrow will worry about itself. Each day has enough trouble of its own.",
    context: "Seek first sets priorities: put God's purposes first and trust the rest. The last line, each day has enough trouble, has an almost Stoic realism. Christians read it as trust in providence, not passivity.",
    today: "One day at a time is still the best advice for heavy seasons.",
    you: "Get your first priority right each morning, then deal only with today's trouble. Tomorrow's will keep.",
  },
  "christianity.23": {
    meaning: "A younger son asks for his inheritance early, travels far and wastes it on wild living. When famine comes he's reduced to feeding pigs and envying their food. He comes to his senses and decides to go home, confess, and ask to be treated as a hired servant.",
    context: "The parable of the Prodigal Son, found only in Luke. Asking for an inheritance early was like wishing the father dead. Feeding pigs was the lowest humiliation for a Jewish listener. The turning point, he came to himself, is a classic picture of repentance.",
    today: "Hitting bottom often brings clarity. Coming to yourself is the start of return.",
    you: "Where have you drifted from what matters most? Coming back starts with admitting it, as the son did.",
  },
  "christianity.24": {
    meaning: "While the son is still far off, his father sees him, is filled with compassion, runs to him and embraces him. Before the son can finish his speech, the father calls for the best robe, a ring and sandals, and a feast: my son was dead and is alive, lost and is found.",
    context: "A dignified father running was undignified in that culture: the point is the eagerness of his love. Christians read the father as God, who welcomes the repentant before they can earn it. The parable continues with an older brother who resents the welcome, a warning about self-righteousness.",
    today: "Welcoming people back after failure, fully and quickly, builds loyalty that punishment never can.",
    you: "When someone who let you down comes back, run to meet them. Restore their standing, not just their job.",
  },
  "christianity.25": {
    meaning: "Two men pray in the temple. The Pharisee thanks God he isn't like other people and lists his religious achievements. The tax collector stands far off, won't look up, and says: God, be merciful to me, a sinner. Jesus says the tax collector went home justified, because the humble will be exalted.",
    context: "Pharisees were respected religious teachers; tax collectors were seen as collaborators with Rome. Jesus reverses the audience's expectations. The tax collector's words became the basis of the Jesus Prayer, repeated by Orthodox Christians in meditation.",
    today: "Comparing ourselves favourably with others is the quickest route to self-deception.",
    you: "Notice when you rehearse your achievements against others. Try the tax collector's honesty instead.",
  },
  "christianity.26": {
    meaning: "Come now, you who say, today or tomorrow we'll go to such a city, trade and make a profit. You don't know what tomorrow will bring. Your life is a mist that appears for a little while and then vanishes. Say instead: if the Lord wills, we'll live and do this or that.",
    context: "James writes practical wisdom for early Christian communities. His phrase if the Lord wills, in Latin Deo volente, became a common Christian habit, echoed in the Islamic insha'Allah. The image of life as a vapour recalls Ecclesiastes.",
    today: "Plans are useful; certainty about them is an illusion.",
    you: "Make your strategic plans, but hold them with a caveat: if circumstances allow. It keeps you adaptable and humble.",
  },
  "christianity.27": {
    meaning: "Paul says he's learned to be content in any situation, with little or with plenty, hungry or full. He's learned the secret of both. He can do all things through Christ who strengthens him.",
    context: "Paul wrote Philippians from prison. Content translates autarkes, self-sufficient, a word the Stoics used; Paul gives it a Christian twist, finding sufficiency in Christ rather than in himself. It's a notable bridge between Stoic and Christian thought.",
    today: "Contentment that doesn't depend on circumstances is a rare and learnable skill.",
    you: "Practise contentment in both directions: when things go well, and when they don't. Paul, like Marcus, learned it in hardship.",
  },
  "christianity.28": {
    meaning: "Everyone wants to know things, but what good is knowledge without reverence for God? A humble peasant who serves God is better than a proud philosopher who studies the stars and neglects to know himself. Knowing all things without love wouldn't help me before God.",
    context: "The Imitation of Christ, attributed to Thomas à Kempis around 1420, is one of the most widely read Christian books after the Bible. It came from the Devotio Moderna, a movement of practical, inward piety in the Low Countries. It's loved by Catholics and many Protestants alike.",
    today: "Expertise without humility or care can make people worse, not better.",
    you: "As someone who builds sophisticated systems, keep asking what the knowledge is for. Clever without kind isn't enough.",
  },
  "christianity.29": {
    meaning: "What good is arguing about the Trinity if you lack humility? Deep words don't make anyone holy; a good life does. Better to feel sorrow for wrongdoing than to define it. Knowing the whole Bible and all philosophy is useless without love. All is vanity except loving and serving God.",
    context: "À Kempis warns against theology as intellectual display. The line about vanity of vanities echoes Ecclesiastes. The book shaped figures as different as Ignatius of Loyola, John Wesley and Thomas More.",
    today: "Practice beats theory. A good life persuades more than a clever argument.",
    you: "Your morning reading is valuable only if it changes the day. Pick one line and live it rather than discuss it.",
  },
  "christianity.30": {
    meaning: "When you pray, go into a private room, shut the door and pray to your Father in secret. Don't babble many words. Pray like this: Our Father in heaven, may your name be holy, your Kingdom come, your will be done; give us today our daily bread; forgive us as we forgive; lead us not into temptation, but deliver us from evil.",
    context: "The Lord's Prayer is prayed by Christians of every tradition, the one prayer they all share. Catholic and Protestant versions differ slightly in ending. Daily bread asks for what's needed today, not a stockpile, and forgiveness is tied to forgiving others.",
    today: "Quiet, private reflection with few words is a discipline many find grounding, religious or not.",
    you: "Your morning session is already a shut door. Keep it private and simple, like this prayer.",
  },
  "christianity.31": {
    meaning: "You are the light of the world. A city on a hill can't be hidden. Nobody lights a lamp and hides it under a basket; they put it on a stand. So let your light shine, so people see your good works and glorify your Father in heaven.",
    context: "This seems to contrast with giving in secret, but Christians read the difference as motive: good works should point to God, not the self. The phrase city on a hill was used by John Winthrop in 1630 and later by American presidents.",
    today: "Visible integrity inspires others. The key is whose glory it serves.",
    you: "Let your team see your good practice, not for credit but so it spreads. Model what you want copied.",
  },
  "christianity.32": {
    meaning: "Whoever hears Jesus's words and does them is like a wise man who built his house on rock: the rain, floods and wind came, and it stood. Whoever hears and doesn't act is like a fool who built on sand, and the house fell with a great crash.",
    context: "This closes the Sermon on the Mount, making practice the point of the whole sermon. Christians across traditions cite it against faith without action; the Letter of James makes the same argument.",
    today: "Foundations are tested in storms, not in good weather.",
    you: "Pick one principle from your recent reading and build on it this week, so it's there when the storm comes.",
  },
  "christianity.33": {
    meaning: "Rulers of the nations lord it over their people, and the great exercise authority. It shall not be so among you. Whoever wants to be great must be your servant, and whoever wants to be first must be your slave, just as the Son of Man came not to be served but to serve and give his life.",
    context: "Jesus says this after two disciples ask for the top seats in his Kingdom. It's the root of the idea of servant leadership, developed in modern management by Robert Greenleaf. Popes use the title servant of the servants of God.",
    today: "Servant leadership is now a mainstream management idea. It started here.",
    you: "Ask of your leadership each week: who did I serve, and what did I clear out of their way?",
  },
  "christianity.34": {
    meaning: "Let love be genuine. Hate evil, cling to good. Love each other warmly, outdo one another in showing honour. Be diligent, hopeful, patient in trouble, faithful in prayer. Share with those in need and show hospitality. Bless those who persecute you. Rejoice and weep with others. Live in harmony, and as far as it depends on you, live at peace with everyone.",
    context: "Paul's letter to the Romans is foundational for Christian theology, especially in Protestant thought. Chapter 12 turns from doctrine to daily life. The qualifier as far as it depends on you is realistic: peace isn't always in our power.",
    today: "It's a compact code for community life: genuine, generous, patient and peace-seeking.",
    you: "Outdo others in showing honour this week: credit colleagues publicly and lavishly.",
  },
  "christianity.35": {
    meaning: "Whatever you do, work at it wholeheartedly, as for the Lord and not for people, knowing you'll receive your reward from the Lord.",
    context: "Paul originally addressed this to servants in Colossae. The Protestant Reformation made it central to the idea of vocation: all honest work, not only religious work, can serve God. Max Weber linked this work ethic to the rise of modern economies.",
    today: "Working for a higher purpose, not just the boss's approval, makes even routine tasks meaningful.",
    you: "When work feels thankless, remember who you're really working for. Do it well whether or not anyone notices.",
  },
  "christianity.36": {
    meaning: "Be doers of the word, not just hearers, or you deceive yourselves. A hearer who doesn't act is like someone who looks in a mirror and immediately forgets what he looks like. Whoever looks into the perfect law of freedom and acts on it will be blessed in what they do.",
    context: "The Letter of James stresses that faith shows itself in action. Martin Luther once called it an epistle of straw because he feared it confused grace with works; most Christians today read James and Paul as complementary.",
    today: "Reading about self-improvement without changing anything is a pleasant form of self-deception.",
    you: "This is the Stoa warning in scripture form. Don't just read the card; act on one thing from it today.",
  },
  "christianity.37": {
    meaning: "The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control. There's no law against such things.",
    context: "Paul contrasts these qualities with the works of the flesh. Fruit is singular: one harvest with many flavours, grown rather than manufactured. Christians see these as signs of God's Spirit at work rather than achievements of willpower.",
    today: "Character grows over time, like fruit, rather than being installed overnight.",
    you: "Pick the fruit you most need, patience perhaps, and look for one chance a day to grow it.",
  },
  "christianity.38": {
    meaning: "Very soon your life here will end, so consider how it will be with you in the next. Today someone is here, tomorrow gone, and soon forgotten. How dull the heart that thinks only of the present. Order every deed and thought as if you were to die today.",
    context: "À Kempis's meditation on death is part of a long Christian tradition of memento mori, remember you'll die. It's close to Marcus Aurelius's instruction to act as if each act were your last, though à Kempis frames it by the life to come.",
    today: "Living as if today mattered ultimately sharpens priorities.",
    you: "Do today's most important task as if it were your last day's work. Then go home and be fully there.",
  },
};
