// Traditions wing explainers: Hinduism (Bhagavad Gita, Ganguli; Upanishads, Paramananda 1919).
// Beliefs are described as the tradition holds them; no ranking of traditions.
export default {
  "hinduism.1": {
    meaning: "Krishna tells Arjuna, who is grieving before a battle, that he mourns what shouldn't be mourned. The wise grieve neither for the dead nor the living. None of us ever didn't exist, nor will we cease to be. Just as the self passes through childhood, youth and age in one body, it passes on to another body.",
    context: "The Bhagavad Gita, the Song of the Lord, is a dialogue within the Mahabharata epic, set on the battlefield of Kurukshetra. Arjuna, a warrior prince, refuses to fight his relatives; Krishna, his charioteer and an incarnation of the god Vishnu, teaches him. This first teaching concerns the atman, the eternal self, which Hindu schools agree survives death.",
    today: "Grief is natural, but seeing life as larger than one body or one moment can steady people in loss.",
    you: "Arjuna's crisis, a leader frozen before a duty that involves harm, is uniquely relevant to defence. Notice how Krishna starts: with perspective, not orders.",
  },
  "hinduism.2": {
    meaning: "Whoever thinks the self kills or is killed understands nothing: it neither kills nor is killed. It is never born and never dies. Unborn, eternal and ancient, it isn't slain when the body is. As a person puts off worn-out clothes and puts on new ones, the embodied self casts off worn-out bodies and enters new ones.",
    context: "This passage is recited at Hindu funerals and is among the most famous in the Gita. The image of changing clothes explains samsara, the cycle of rebirth. Philosophers of the Advaita school, following Shankara, read it as showing the self is identical with ultimate reality; devotional schools read it as the soul's journey toward God.",
    today: "The idea that the core of a person is untouched by what happens to the body has comforted people facing death for millennia.",
    you: "Whatever you believe about rebirth, the teaching separates your deepest self from roles and outcomes. That separation is steadying under pressure.",
  },
  "hinduism.3": {
    meaning: "Krishna says: whenever righteousness declines and unrighteousness rises, I bring myself forth. To protect the good, destroy evildoers and establish righteousness, I am born age after age.",
    context: "These verses express the doctrine of the avatar, God descending into the world. Vaishnava Hindus hold that Vishnu has taken many forms, including Rama and Krishna. The word translated piety is dharma, cosmic and moral order, one of the central ideas of Hindu thought.",
    today: "The belief that order will be restored when things go badly wrong has sustained many communities through dark times.",
    you: "In periods of institutional decline, someone has to act to restore good order. Ask whether it's your turn.",
  },
  "hinduism.4": {
    meaning: "Everything in the universe should be covered by the Lord, seen as filled with God. Having renounced what is unreal, enjoy what is real. Don't covet anyone's wealth.",
    context: "This is the first verse of the Isha Upanishad, one of the shortest and most important of the Upanishads, the philosophical texts at the end of the Vedas. Mahatma Gandhi said that if all the scriptures were lost and only this verse survived, Hinduism would live. The idea is to enjoy life through renunciation, not greed.",
    today: "Enjoying what you have, without grasping at what others have, is a recipe for contentment.",
    you: "Enjoy your life by holding it lightly. And don't covet a colleague's promotion or a neighbour's house.",
  },
  "hinduism.5": {
    meaning: "Whoever sees all beings in the Self and the Self in all beings never turns away from it. For one who sees all beings as the Self, what delusion or grief can there be, when they see this oneness everywhere?",
    context: "These verses express the Upanishadic insight that the atman, the self within, is one with Brahman, the reality behind all things. Advaita Vedanta takes this as strict non-duality; other schools, like Ramanuja's, see souls as distinct but inseparable from God. Either way it grounds an ethic of seeing others as oneself.",
    today: "If others are, in some deep sense, ourselves, cruelty becomes self-harm. It's a powerful foundation for compassion.",
    you: "Try this lens with a difficult person: see the same life in them as in you. Notice whether your response changes.",
  },
  "hinduism.6": {
    meaning: "That which speech does not illumine, but which illumines speech; which the mind cannot think, but by which the mind thinks; which the eye cannot see, but by which the eye sees: know that alone as Brahman, not what people worship here.",
    context: "The Kena Upanishad, named after its first word, kena, by whom, asks what powers the senses and mind. Its answer is that Brahman is the subject behind all experience and can never become an object. The phrase not this which people worship warns against mistaking any image or idea for the ultimate.",
    today: "Awareness itself is the one thing we can never look at directly. The puzzle still fascinates philosophers of mind.",
    you: "As someone who builds sensing systems, notice the question: what is it that knows? No sensor answers it.",
  },
  "hinduism.7": {
    meaning: "Know the Self as the lord of a chariot, the body as the chariot, the intellect as the driver and the mind as the reins. The senses are the horses and the objects of sense are the roads.",
    context: "The Katha Upanishad frames its teaching as a dialogue between the boy Nachiketas and Yama, the god of death. The chariot image resembles Plato's charioteer in the Phaedrus, a striking parallel between Indian and Greek thought. The goal is for intellect, buddhi, to steer the mind and senses well.",
    today: "It's a clear model of self-control: judgement drives, attention holds the reins, desires pull.",
    you: "Use the chariot as a daily check: who is driving today, your judgement or your horses?",
  },
  "hinduism.8": {
    meaning: "Whoever offers Krishna a leaf, a flower, fruit or water with devotion, he accepts it from the pure-hearted. Whatever you do, eat, give or endure, do it as an offering to him.",
    context: "These verses are central to bhakti, the path of loving devotion, which is the most widely practised form of Hinduism. The simplicity of the offering, a leaf or water, stresses the heart over wealth. Offering all actions to God turns daily life into worship.",
    today: "Small acts, done with care, can carry great meaning. Motive transforms the ordinary.",
    you: "Offer today's work, whatever it is, to something higher than your career: your family, your country, or God.",
  },
  "hinduism.9": {
    meaning: "The divine qualities: fearlessness, purity of heart, steadiness in knowledge and meditation, generosity, self-control, study, austerity, honesty, non-harm, truth, freedom from anger, renunciation, calm, avoiding fault-finding, compassion for all, freedom from greed, gentleness, modesty, vigour, forgiveness, firmness, cleanliness, and freedom from vanity.",
    context: "Chapter 16 contrasts divine, daivi, and demonic, asuri, dispositions. The list is a compact Hindu catalogue of virtues. Ahimsa, non-harm, appears here; Gandhi made it a principle of political action, though the Gita itself is set on a battlefield and interpreters differ on how the two fit.",
    today: "It's a rich virtue list for self-examination, with fearlessness first.",
    you: "Fearlessness leads the list, and freedom from vanity closes it. Both matter in leadership. Which do you need more?",
  },
  "hinduism.10": {
    meaning: "The wise look with an equal eye on a learned and modest priest, a cow, an elephant, a dog and an outcaste.",
    context: "This verse teaches sama-darshana, equal vision: the same self lives in all beings. The mention of an outcaste, chandala, challenged caste hierarchy; reformers from the medieval poet-saints to modern campaigners cited it, though traditional society often fell short of it.",
    today: "Seeing equal worth in everyone regardless of status is still radical in practice.",
    you: "Watch how you treat the most junior person in the room compared with the most senior. Aim for an equal eye.",
  },
  "hinduism.11": {
    meaning: "Dear to Krishna is one who hates no creature, is friendly and compassionate, free of ego and vanity, the same in pleasure and pain, forgiving and content, firm and devoted. Dear is one who doesn't trouble the world and isn't troubled by it, free of excitement, anger, fear and anxiety.",
    context: "Chapter 12 describes the ideal devotee of the bhakti path. These verses are often recited as a portrait of the saintly person. Their emphasis on equanimity and goodwill connects devotion with ethics.",
    today: "Not troubling the world and not being troubled by it is a fine description of calm maturity.",
    you: "Aim to be the steady presence on your team: not adding to anxiety, and not caught by it.",
  },
  "hinduism.12": {
    meaning: "Speech that causes no distress, that is true, pleasant and beneficial, along with regular study, is the discipline of speech. Calm of mind, gentleness, silence, self-control and purity of heart are the discipline of the mind.",
    context: "Chapter 17 describes tapas, disciplines or austerities, of body, speech and mind. The test for speech, true, kind and beneficial, is similar to Buddhist right speech. Hindu teachers often cite it as a guide to everyday communication.",
    today: "True, kind and useful: a three-part filter for anything you say or post.",
    you: "Before your next critical email, run the filter: is it true, is it kind, is it useful?",
  },
  "hinduism.13": {
    meaning: "Always do the work that should be done, without attachment. By working without attachment one reaches the highest. King Janaka and others reached perfection through action. Consider the good of the world: whatever a great person does, others follow; people follow the standard they set.",
    context: "Chapter 3 teaches karma yoga, the discipline of selfless action. Janaka was a philosopher-king who remained active in the world. The idea that leaders set the standard, lokasangraha, holding the world together, is a key political idea in the Gita.",
    today: "Leaders are copied. Their conduct becomes the norm, for good or ill.",
    you: "Whatever you do, your team will copy. Set the standard you'd want everyone to follow.",
  },
  "hinduism.14": {
    meaning: "One who regards well-wishers, friends, enemies, neutrals, mediators, the hateful, relatives, the good and the wicked with an equal mind stands out above others.",
    context: "Chapter 6 describes the yogi's equanimity, samatva. This isn't indifference; it is freedom from bias in judgement. Commentators note that the Gita asks for inner evenness while still acting rightly towards each person.",
    today: "Treating allies and opponents with the same fairness is rare and respected.",
    you: "In negotiations and assessments, aim for this evenness: the same fairness to rivals as to friends.",
  },
  "hinduism.15": {
    meaning: "Contacts of the senses with their objects give heat and cold, pleasure and pain. They come and go and don't last. Endure them. The person untroubled by them, the same in pleasure and pain, is fit for liberation.",
    context: "Titiksha, forbearance, is part of Hindu spiritual training. The passage echoes the Stoic view that impressions come and go and needn't disturb us. Liberation, moksha, is the ultimate goal in Hindu thought.",
    today: "Discomforts pass. Learning to bear them without drama is a lifelong asset.",
    you: "The Gita and Marcus agree here. When discomfort hits, name it as passing and carry on.",
  },
  "hinduism.16": {
    meaning: "Dwelling on objects of the senses breeds attachment; attachment breeds desire and then anger; anger clouds judgement; clouded judgement ruins memory; ruined memory destroys understanding; and with understanding lost, a person is ruined.",
    context: "This chain, from attention to ruin, is one of the Gita's most quoted analyses of the mind. It shows how inner states compound. Commentators see it as the reason for guarding attention in the first place.",
    today: "It maps how compulsive attention turns into craving and then frustration, the dynamics of the feed.",
    you: "The chain starts with where attention rests. Guarding your inputs, as you've done by leaving Instagram, protects everything downstream.",
  },
  "hinduism.17": {
    meaning: "The one into whom desires flow as rivers flow into the ocean, which stays full and unmoved, finds peace, not the one who chases desires.",
    context: "The image of the ocean describes the sthitaprajna, the person of steady wisdom, whose depth absorbs desires without being disturbed. Chapter 2 ends with this portrait, which Gandhi said he tried to live by.",
    today: "Wants will keep arriving. Depth, not suppression, keeps you steady.",
    you: "Be the ocean this week: notice wants arriving, and let them settle without being moved by them.",
  },
  "hinduism.18": {
    meaning: "Raise yourself by your own self and don't degrade yourself. Your self can be your friend or your enemy. For one who has mastered themselves, the self is a friend; for one who hasn't, it acts like an enemy. The self-mastered person is steady in cold and heat, pleasure and pain, honour and dishonour.",
    context: "This passage emphasises self-effort in spiritual growth. Hindu schools debate the balance of effort and divine grace; this verse is a favourite of those who stress effort. The words for self and mind overlap in Sanskrit, atman and manas, so it can also mean the mind is friend or foe.",
    today: "The same mind that sabotages us can be trained into our best ally.",
    you: "Treat your own mind as a colleague to train, not an enemy to fight. What small habit makes it more of a friend?",
  },
  "hinduism.19": {
    meaning: "As a lamp in a windless place does not flicker: that is the image of a meditator whose mind is controlled.",
    context: "Chapter 6 teaches dhyana, meditation. The steady flame is a classic image used by teachers across Hindu, Buddhist and Jain traditions. The instructions around it cover posture, moderation and gradual training of attention.",
    today: "A steady mind in a noisy world is a rare and trainable thing.",
    you: "Picture the still flame during a hectic day. A minute of steadiness helps judgement more than an hour of noise.",
  },
  "hinduism.20": {
    meaning: "Arjuna says: Krishna, the mind is restless, turbulent, strong and stubborn. Controlling it seems as hard as controlling the wind.",
    context: "Krishna's reply, in the next verse, is that the mind can be trained by abhyasa, practice, and vairagya, detachment. These two words became foundations of Hindu yoga teaching, and appear in Patanjali's Yoga Sutras as well.",
    today: "Honest admission that the mind is hard to control is the first step to training it.",
    you: "Practice and detachment: the two tools Krishna offers. Your daily reading is practice; letting go of the feed is detachment.",
  },
  "hinduism.21": {
    meaning: "Yama says: the good and the pleasant are different, and both bind a person. It goes well for the one who chooses the good; the one who chooses the pleasant misses the goal. The wise examine both and choose the good; the foolish choose the pleasant out of desire.",
    context: "Nachiketas has refused Yama's offers of wealth and pleasure in favour of knowledge. The contrast between shreyas, the good, and preyas, the pleasant, is one of the best-known ideas in the Upanishads. It anticipates Aristotle's distinction between true good and apparent good.",
    today: "Most daily choices are between what feels good now and what is good. Naming the difference helps.",
    you: "The feed is preyas; this session is shreyas. Name which one you're choosing next time you pick up your phone.",
  },
  "hinduism.22": {
    meaning: "The happiness that comes from the senses meeting their objects is like nectar at first and poison in the end. That happiness belongs to the quality of passion.",
    context: "The Gita classifies things by three gunas, qualities of nature: sattva, goodness; rajas, passion; and tamas, darkness. Sattvic happiness, it says just before this, is like poison at first and nectar in the end, the reverse pattern.",
    today: "Nectar first, poison later: an exact description of compulsive scrolling and many modern pleasures.",
    you: "Use the test on your habits: nectar first and poison later, or bitter first and nectar later? Choose the second.",
  },
  "hinduism.23": {
    meaning: "Your concern is with the work alone, never with its fruits. Don't let the fruit be your motive, and don't be attached to inaction. Established in yoga, act without attachment, the same in success and failure. That evenness is called yoga.",
    context: "This is the most quoted teaching of the Gita, the heart of karma yoga. The plan compares it with Marcus Aurelius on doing good without looking for reward. Yoga here means evenness or discipline, samatva, not physical postures.",
    today: "Focusing on doing the work well, not on outcomes you can't control, reduces anxiety and improves the work.",
    you: "This is the antidote to the Metric Cage: judge yourself by the quality of the work, not by the numbers it produces.",
  },
  "hinduism.24": {
    meaning: "Yoga is skill in action. The wise, established in it, give up the fruits of action, are freed from the bonds of rebirth, and reach a state beyond sorrow.",
    context: "Yogah karmasu kaushalam, yoga is skill in action, is a famous definition; it is the motto of several Indian institutions. Ganguli translates yoga as devotion and skill as cleverness. The point is that detached action is also better action.",
    today: "Detachment doesn't mean doing less; it means doing it with more skill and less fear.",
    you: "When you care less about how an outcome reflects on you, you often perform better. Test it on your next presentation.",
  },
  "hinduism.25": {
    meaning: "Better your own duty done imperfectly than another's done well. Death in your own duty is better; another's duty brings danger.",
    context: "Svadharma, your own duty, reflects your nature and station in life. Traditional society tied it to caste and stage of life; many modern Hindus read it as vocation, the work that fits who you are.",
    today: "Living your own calling, even clumsily, beats imitating someone else's life.",
    you: "Don't copy another leader's path. Do your own work, suited to your gifts, even if it's harder.",
  },
  "hinduism.26": {
    meaning: "Whoever gives up attachment to the fruits of action, is always content and depends on nothing, does nothing at all, even while acting.",
    context: "This is the paradox of naishkarmya, action without binding effect: when ego and craving drop away, action no longer creates karmic bondage. Hindu teachers compare it to an actor playing a role fully without confusing it with who they are.",
    today: "Work done without craving for its rewards leaves no residue of anxiety.",
    you: "Play your roles fully, leader, parent, colleague, while remembering they're roles. It keeps you free.",
  },
  "hinduism.27": {
    meaning: "Whoever acts while giving up attachment, offering actions to Brahman, is untouched by wrong, as a lotus leaf is untouched by water.",
    context: "The lotus grows in muddy water but its leaves stay dry and clean, a symbol of purity in the world across Hindu and Buddhist art. The verse teaches that one can live fully in the world without being stained by it.",
    today: "It's possible to work in messy environments without becoming messy yourself.",
    you: "Politics and bureaucracy can be muddy. Be the lotus leaf: engaged, effective and unstained.",
  },
  "hinduism.28": {
    meaning: "Yoga isn't for one who eats too much or not at all, sleeps too much or too little. It is for one moderate in food and recreation, in effort at work, and in sleep and waking.",
    context: "The Gita rejects extreme asceticism as much as indulgence, a middle way similar to the Buddha's. Yukta, balanced or disciplined, is the key word. Modern Hindu teachers often cite this verse in discussing health and work-life balance.",
    today: "Balance in eating, sleeping, working and resting is still the foundation of wellbeing.",
    you: "Check your sleep and working hours honestly. The Gita counts moderation as spiritual practice.",
  },
  "hinduism.29": {
    meaning: "An embodied person can't give up action entirely, so whoever gives up the fruits of action is the true renouncer.",
    context: "Chapter 18 sums up the Gita's teaching: true renunciation, tyaga, is not leaving the world but giving up selfish attachment within it. This reconciled the ascetic ideal with ordinary life for householders.",
    today: "You don't need to withdraw from the world to be free of it.",
    you: "Stay fully engaged in your work and family; renounce only the need to control results.",
  },
  "hinduism.30": {
    meaning: "Arise! Awake! Find the great teachers and learn from them. The path is sharp as a razor's edge, hard to cross, so the wise say.",
    context: "Uttishthata jagrata, arise, awake, from the Katha Upanishad, became the rallying call of Swami Vivekananda, who brought Vedanta to the West in the 1890s. The razor's edge gave its name to a novel by Somerset Maugham.",
    today: "Growth requires waking up, finding good teachers, and accepting that the way is demanding.",
    you: "Seek out the great teachers in your field and learn from them directly. Then walk the narrow path with care.",
  },
};
